<a href="https://colab.research.google.com/github/Allen123321/DEMO-DL/blob/master/%E7%BC%BA%E7%9C%81%E5%80%BC%E5%A1%AB%E5%85%85_%26_%E4%BA%9A%E7%BC%96%E7%A0%81_%26_%E4%BA%8C%E5%80%BC%E5%8C%96_%26_%E6%A0%87%E5%87%86%E5%8C%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from sklearn import impute

In [7]:
X = [
    [2, 2, 4, 1],
    [np.nan, 3, 4, 4],
    [1, 1, 1, np.nan],
    [2, 2, np.nan, 3]
]
X2 = [
    [2, 6, np.nan, 1],
    [np.nan, 5, np.nan, 1],
    [4, 1, np.nan, 5],
    [np.nan, np.nan, np.nan, 1]
]

In [9]:
imp1 = impute.SimpleImputer(missing_values= np.nan,strategy='mean')
imp2 = impute.SimpleImputer(missing_values=np.nan,strategy='mean')
imp1.fit(X)
imp2.fit(X)


SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [10]:
print (imp1.transform(X2))
print ("--------------------------")
print (imp2.transform(X2))

[[2.         6.         3.         1.        ]
 [1.66666667 5.         3.         1.        ]
 [4.         1.         3.         5.        ]
 [1.66666667 2.         3.         1.        ]]
--------------------------
[[2.         6.         3.         1.        ]
 [1.66666667 5.         3.         1.        ]
 [4.         1.         3.         5.        ]
 [1.66666667 2.         3.         1.        ]]


In [11]:
imp3 = impute.SimpleImputer(missing_values=np.nan,strategy='mean')
imp4 = impute.SimpleImputer(missing_values=np.nan,strategy='median')
imp5 = impute.SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imp3.fit(X)
imp4.fit(X)
imp5.fit(X)


SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [13]:
print (X)
print (X2)
print ("--------------------------")
print (imp3.transform(X2))
print ("--------------------------")
print (imp4.transform(X2))
print ("--------------------------")
print (imp5.transform(X2))

[[2, 2, 4, 1], [nan, 3, 4, 4], [1, 1, 1, nan], [2, 2, nan, 3]]
[[2, 6, nan, 1], [nan, 5, nan, 1], [4, 1, nan, 5], [nan, nan, nan, 1]]
--------------------------
[[2.         6.         3.         1.        ]
 [1.66666667 5.         3.         1.        ]
 [4.         1.         3.         5.        ]
 [1.66666667 2.         3.         1.        ]]
--------------------------
[[2. 6. 4. 1.]
 [2. 5. 4. 1.]
 [4. 1. 4. 5.]
 [2. 2. 4. 1.]]
--------------------------
[[2. 6. 4. 1.]
 [2. 5. 4. 1.]
 [4. 1. 4. 5.]
 [2. 2. 4. 1.]]


In [14]:
from numpy import random
x=random.RandomState(1)
0.5-x.rand(14)

array([ 0.082978  , -0.22032449,  0.49988563,  0.19766743,  0.35324411,
        0.40766141,  0.31373979,  0.15443927,  0.10323253, -0.03881673,
        0.08080549, -0.1852195 ,  0.29554775, -0.37811744])

哑编码

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import DictVectorizer,FeatureHasher
import numpy as np

In [19]:
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2],[1,1,1]]) 
a=np.array([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])
print(a)
# 基于列进行编码
print(enc.categories_)

[[0 0 3]
 [1 1 0]
 [0 2 1]
 [1 0 2]]
[array([0, 1]), array([0, 1, 2]), array([0, 1, 2, 3])]


In [20]:
# 把0放到第一列[0,1]比对，把1放到第二列[0,1,2]比对，把3放到第三列[0,1,2，3]比对
enc.transform([[0, 1, 3]]).toarray()

array([[1., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [23]:
# 将特征值映射列表转换为向量
dv = DictVectorizer(sparse=False)
D = [{'foo':1, 'bar':2}, {'foo':3, 'baz': 2}]
X = dv.fit_transform(D)
print (X)
print (dv.get_feature_names())
print (dv.transform({'foo':4, 'unseen':3}))

[[2. 0. 1.]
 [0. 2. 3.]]
['bar', 'baz', 'foo']
[[0. 0. 4.]]


In [27]:
# hash转换
h = FeatureHasher(n_features=10)
D = [{'dog': 1, 'cat':2, 'elephant':4},{'dog': 2, 'run': 5}]
f = h.transform(D)
f.toarray()

array([[ 0.,  0., -4., -1.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0., -2., -5.,  0.,  0.,  0.,  0.,  0.]])

二值化

In [28]:
import numpy as np
from sklearn.preprocessing import Binarizer

In [29]:
arr = np.array([
    [1.5, 1.3, 1.9],
    [0.5, 0.5, 1.6],
    [1.1, 2.1, 0.2]
])

In [32]:
binarizer = Binarizer(threshold=1.4).fit(arr)
binarizer

Binarizer(copy=True, threshold=1.4)

In [33]:
binarizer.transform(arr)

array([[1., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

标准化

In [35]:
from sklearn.preprocessing import StandardScaler


In [36]:
X = [
    [1, 2, 3, 2],
    [7, 8, 9, 2.01],
    [4, 8, 2, 2.01],
    [9, 5, 2, 1.99],
    [7, 5, 3, 1.99],
    [1, 4, 9, 2]
]

In [37]:
ss = StandardScaler(with_mean=True, with_std=True)
ss.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [39]:
print(ss.mean_)
print(ss.n_samples_seen_)
print(ss.scale_)

[4.83333333 5.33333333 4.66666667 2.        ]
6
[3.07769755 2.13437475 3.09120617 0.00816497]


In [40]:
print(ss.transform(X))

[[-1.24551983 -1.56173762 -0.53916387  0.        ]
 [ 0.70398947  1.2493901   1.40182605  1.22474487]
 [-0.27076518  1.2493901  -0.86266219  1.22474487]
 [ 1.3538259  -0.15617376 -0.86266219 -1.22474487]
 [ 0.70398947 -0.15617376 -0.53916387 -1.22474487]
 [-1.24551983 -0.62469505  1.40182605  0.        ]]
