<a href="https://colab.research.google.com/github/Allen123321/DEMO-DL/blob/master/BP%E7%AE%97%E6%B3%95%E7%AE%80%E5%8D%95%E5%AE%9E%E7%8E%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#例子：1
import numpy as np

In [6]:
def sigmoid(x):
  return 1/(1+ np.exp(-x))

def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))





In [27]:
class BPNetWork(object):
  def __init__(self):
    self.alpha = 0.5   #学习率
    self.W1 = np.array([[0.5,0.2],[0.25,0.30]],dtype=float)    #输入层到卷积层的系数矩阵
    self.b1 = np.array([[0.35],[0.35]])
    self.W2 = np.array([[0.45,0.45],[0.50,0.55]],dtype=float)
    self.b2 = np.array([[0.9],[0.6]],dtype=float)
    self.input = np.array([[0.05],[0.10]],dtype=float)
    self.output = np.array([[0.05],[0.9]],dtype=float)

  # def __call__(self,):
  #   feedfoward(self)
  #   propogate(self)


  def feedfoward(self):
    Z1 = np.matmul(self.W1,self.input) + self.b1
    A1 = sigmoid(Z1)
    Z2 = np.matmul(self.W2,A1) + self.b2
    A2 = sigmoid(Z2)
    return Z1,A1,Z2,A2

  def propogate(self):
    z1,a1,z2,a2=self.feedfoward()
    delta2=-(self.output-a2)*sigmoid_der(z2)
    self.W2-=(self.alpha)*np.matmul(delta2,np.transpose(a1))
    self.b2-=self.alpha*delta2

    delta1=np.matmul(np.transpose(self.W2),delta2)*sigmoid_der(z2)
    self.W1-=self.alpha*np.matmul(np.transpose(self.input),delta1)
    self.b1-=self.alpha*delta1


In [28]:

BP = BPNetWork()
BP.__init__()

for i in range(10000):
    BP.propogate()
    
    if i%100==0:
        _,_,_,a2=BP.feedfoward()
        print(a2)


[[0.79185218]
 [0.77647765]]
[[0.11532262]
 [0.87498663]]
[[0.0828854 ]
 [0.89067199]]
[[0.0709064 ]
 [0.89605825]]
[[0.06455874]
 [0.89828099]]
[[0.0606404 ]
 [0.89925821]]
[[0.05800992]
 [0.89969574]]
[[0.05614921]
 [0.89989034]]
[[0.05478602]
 [0.89997434]]
[[0.05376233]
 [0.90000825]]
[[0.05297963]
 [0.90001989]]
[[0.05237311]
 [0.90002203]]
[[0.05189827]
 [0.90002043]]
[[0.0515236 ]
 [0.90001764]]
[[0.05122614]
 [0.90001473]]
[[0.05098883]
 [0.90001208]]
[[0.05079879]
 [0.90000983]]
[[0.05064614]
 [0.90000797]]
[[0.05052322]
 [0.90000645]]
[[0.05042406]
 [0.90000522]]
[[0.05034392]
 [0.90000422]]
[[0.05027909]
 [0.90000342]]
[[0.05022658]
 [0.90000277]]
[[0.05018402]
 [0.90000224]]
[[0.0501495 ]
 [0.90000182]]
[[0.05012148]
 [0.90000148]]
[[0.05009874]
 [0.9000012 ]]
[[0.05008026]
 [0.90000097]]
[[0.05006525]
 [0.90000079]]
[[0.05005305]
 [0.90000064]]
[[0.05004314]
 [0.90000052]]
[[0.05003508]
 [0.90000042]]
[[0.05002853]
 [0.90000034]]
[[0.0500232 ]
 [0.90000028]]
[[0.05001887]


例子二

In [29]:
#训练数据：经典的异或分类问题
train_X = np.array([[0,0],[0,1],[1,0],[1,1]])
train_y = np.array([0,1,1,0])


In [37]:
#我们定义一个简单的2层神经网络：
class LinearLayer:
  def __init__(self, input_D, output_D):
    self._W = np.random.normal(0, 0.1, (input_D, output_D)) #初始化不能为全0
    self._b = np.random.normal(0, 0.1, (1, output_D))
    self._grad_W = np.zeros((input_D, output_D))
    self._grad_b = np.zeros((1, output_D))

  def forward(self, X):
    return np.matmul(X, self._W) + self._b

  def backward(self, X, grad): 
    self._grad_W = np.matmul( X.T, grad)
    self._grad_b = np.matmul(grad.T, np.ones(X.shape[0]))

    return np.matmul(grad, self._W.T)

  def update(self, learn_rate):
    self._W = self._W - self._grad_W * learn_rate
    self._b = self._b - self._grad_b * learn_rate


class Relu:
    def __init__(self):
        pass

    def forward(self, X):
        return np.where(X < 0, 0, X)

    def backward(self, X, grad):
        return np.where(X > 0, 1, 0) * grad



linear1 = LinearLayer(2,3)
relu1 = Relu()
linear2 = LinearLayer(3,1)


In [38]:

def MSELoss(x, y):
    assert x.shape == y.shape
    return np.linalg.norm( x - y) ** 2



#训练网络
for i in range(10000):

    #前向传播Forward，获取网络输出
    o0 = train_X
    a1 = linear1.forward(o0)
    o1 = relu1.forward(a1)
    a2 = linear2.forward(o1)
    o2 = a2

    #获得网络当前输出，计算损失loss
    y = o2.reshape(o2.shape[0])
    loss = MSELoss(train_y, y) # MSE损失函数

    #反向传播，获取梯度
    grad = (y - train_y).reshape(y.shape[0],1)
    grad = linear2.backward(o1, grad)
    grad = relu1.backward(a1, grad)
    grad = linear1.backward(o0, grad)

    learn_rate = 0.01  #学习率

    #更新网络中线性层的参数
    linear1.update(learn_rate)
    linear2.update(learn_rate)

    #判断学习是否完成
    if i % 200 == 0:
        print(loss)
    if loss < 0.001:
        print("训练完成！ 第%d次迭代" %(i))
        break



1.7718479356202606
0.9144378569080922
0.7820553960749708
0.6600099325538413
0.536911941045257
0.24263641783374074
0.0354826197310999
0.003345178376605887
训练完成！ 第1505次迭代


In [39]:
#将训练好的参数拼成一个网络模型
model = [linear1, relu1, linear2]

In [40]:
#用训练好的模型去预测
def predict(model, X):
    tmp = X
    for layer in model:
        tmp = layer.forward(tmp)
    return np.where(tmp > 0.5, 1, 0)


#开始预测
print("-----")
X = np.array([[0,0],[0,1],[1,0],[1,1]])
result = predict(model, X)
print("预测数据1")
print(X)
print("预测结果1")
print(result)

-----
预测数据1
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
预测结果1
[[0]
 [1]
 [1]
 [0]]
