<a href="https://colab.research.google.com/github/Allen123321/DEMO-DL/blob/master/%E5%8C%BA%E9%97%B4%E7%BC%A9%E6%94%BE%26%E7%89%B9%E5%BE%81%E9%80%89%E6%8B%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

区间缩放

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
X = np.array([
              [1,-1,2,3],
              [2,0,0,3],
              [0,1,-1,3]
],dtype = np.float64)

In [3]:
scaler = MinMaxScaler(feature_range=(1,5))
scaler.fit(X)

MinMaxScaler(copy=True, feature_range=(1, 5))

In [5]:
print(scaler.data_max_)
print(scaler.data_min_)
print(scaler.data_range_)

[2. 1. 2. 3.]
[ 0. -1. -1.  3.]
[2. 2. 3. 0.]


In [6]:
print(scaler.transform(X))

[[3.         1.         5.         1.        ]
 [5.         3.         2.33333333 1.        ]
 [1.         5.         1.         1.        ]]


归一化

In [7]:
import numpy as np
from sklearn.preprocessing import Normalizer

In [8]:
X1 = np.array([
    [1, -1, 2],
    [2, 0, 0],
    [0, 1, -1]
], dtype=np.float64)

In [9]:
normalizer1 = Normalizer(norm='max')
normalizer2 = Normalizer(norm='l2')
normalizer1.fit(X)
normalizer2.fit(X)

Normalizer(copy=True, norm='l2')

In [10]:
print(normalizer1.transform(X1))
print("----------------------------------")
print(normalizer2.transform(X1))

[[ 0.5 -0.5  1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -1. ]]
----------------------------------
[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


多项式转换

In [11]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [12]:
X2= np.arange(6).reshape(3,2)
X2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
poly1 = PolynomialFeatures(2)
poly1.fit(X2)

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')

In [14]:
print(poly1)
print(poly1.transform(X2))

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [15]:
poly2 = PolynomialFeatures(interaction_only= True)
poly2.fit(X2)
print(poly2)
print(poly2.transform(X2))

PolynomialFeatures(degree=2, include_bias=True, interaction_only=True,
                   order='C')
[[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]


In [16]:
poly3 = PolynomialFeatures(include_bias=False)
poly3.fit(X2)
print(poly3)
print(poly3.transform(X2))

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')
[[ 0.  1.  0.  0.  1.]
 [ 2.  3.  4.  6.  9.]
 [ 4.  5. 16. 20. 25.]]


特征选择

In [17]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold,SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingClassifier

In [25]:
X3 = np.array([
    [0, 2, 0, 3],
    [0, 1, 4, 3],
    [0.1, 1, 1, 3]
], dtype=np.float64)
Y = np.array([1,2,1])

In [26]:
variance = VarianceThreshold(threshold=0.1)
print(variance)
variance.fit(X3)
print(variance.transform(X3))

VarianceThreshold(threshold=0.1)
[[2. 0.]
 [1. 4.]
 [1. 1.]]


In [27]:
sk1 = SelectKBest(f_regression,k=2)
sk1.fit(X3,Y)
print(sk1)
print(sk1.scores_)
print(sk1.transform(X3))

SelectKBest(k=2, score_func=<function f_regression at 0x7f6ec381d158>)
[ 0.33333333  0.33333333 16.33333333         nan]
[[0.  0. ]
 [0.  4. ]
 [0.1 1. ]]


/usr/local/lib/python3.6/dist-packages/sklearn/feature_selection/_univariate_selection.py:299: RuntimeWarning: divide by zero encountered in true_divide
  corr /= X_norms
/usr/local/lib/python3.6/dist-packages/sklearn/feature_selection/_univariate_selection.py:304: RuntimeWarning: invalid value encountered in true_divide
  F = corr ** 2 / (1 - corr ** 2) * degrees_of_freedom
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


卡方检验 自变量对定性因变量的相关性

In [28]:
sk2 = SelectKBest(chi2, k=2)
sk2.fit(X3, Y)
print(sk2)
print(sk2.scores_)
print(sk2.transform(X3))

SelectKBest(k=2, score_func=<function chi2 at 0x7f6ec381d0d0>)
[0.05  0.125 4.9   0.   ]
[[2. 0.]
 [1. 4.]
 [1. 1.]]


递归特征消除法：使用一个基模型来进行多轮训练，每轮训练后，消除若干权值系数的特征，在基于新的特征集进行下一轮的训练。

In [30]:
estimator = SVR(kernel='linear')
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X3, Y)
print(selector.support_)
print(selector.n_features_)
print(selector.ranking_)
print(selector.transform(X3))

[False  True  True False]
2
[2 1 1 3]
[[2. 0.]
 [1. 4.]
 [1. 1.]]


基于惩罚项的选择方法，

In [33]:
X4 = np.array([
    [ 5.1,  3.5,  1.4,  0.2],
    [ 4.9,  3. ,  1.4,  0.2],
    [ -6.2,  0.4,  5.4,  2.3],
    [ -5.9,  0. ,  5.1,  1.8]
], dtype=np.float64)
Y4 = np.array([0, 0, 2, 2])
estimator = LogisticRegression(penalty='l1', C=0.1,solver='liblinear')
sfm = SelectFromModel(estimator)
sfm.fit(X4,Y4)
print(sfm.transform(X4))

[[ 5.1]
 [ 4.9]
 [-6.2]
 [-5.9]]


In [34]:
estimator = GradientBoostingClassifier()
sfm = SelectFromModel(estimator)
sfm.fit(X4, Y4)
print(sfm.transform(X4))

[[ 5.1  3.5]
 [ 4.9  3. ]
 [-6.2  0.4]
 [-5.9  0. ]]


特征选取
主成分分析，降维




In [36]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X4)
print(pca.mean_)
print(pca.components_)
print(pca.transform(X4))

[-0.525  1.725  3.325  1.125]
[[-0.90319637 -0.24920124  0.31484024  0.15169269]
 [ 0.03919747 -0.80616444 -0.27357029 -0.52318424]]
[[-6.26919501 -0.19988789]
 [-5.96395512  0.19535484]
 [ 6.28736349 -0.33667759]
 [ 5.94578665  0.34121064]]


线性判别分析法

In [37]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
lda = LinearDiscriminantAnalysis(n_components=2)
lda.fit(X4, Y4)
print(lda.transform(X4))


[[-27.18468036]
 [-25.44008732]
 [ 26.80136112]
 [ 25.82340656]]


/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:463: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(4, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:469: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
