<a href="https://colab.research.google.com/github/Allen123321/DEMO-DL/blob/master/007_TensorFlow2%E6%95%99%E7%A8%8B_%E4%B8%8D%E8%A7%84%E5%88%99%E5%90%91%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
import tensorflow as tf

数据有多种形式。张量也应该如此。 不规则的张量是嵌套可变长度列表的TensorFlow等效项。它们使存储和处理形状不均匀的数据变得容易，包括：

+ 可变长度功能，例如电影中的一组演员。
+ 成批的可变长度顺序输入，例如句子或视频剪辑。
+ 分层输入，例如细分为小节，段落，句子和单词的文本文档。
+ 结构化输入中的各个字段，例如协议缓冲区。


## 1 不规则张量的作用
不规则张量受一百多个TensorFlow操作的支持，其中包括数学操作（如tf.add和tf.reduce_mean），数组操作（如tf.concat和tf.tile），字符串操作op（如 tf.substr）以及许多其他功能：

In [2]:
digits = tf.ragged.constant([[3,1,4,1], [], [5,9,2], [6],[]])
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])


In [3]:
print(tf.add(digits, 3))

<tf.RaggedTensor [[6, 4, 7, 4], [], [8, 12, 5], [9], []]>


In [4]:
print(tf.reduce_mean(digits, axis=1))

tf.Tensor([2.25              nan 5.33333333 6.                nan], shape=(5,), dtype=float64)


In [5]:
print(tf.concat([digits, [[5, 3]]], axis=0))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], [], [5, 3]]>


In [6]:
print(tf.tile(digits, [1, 2]))

<tf.RaggedTensor [[3, 1, 4, 1, 3, 1, 4, 1], [], [5, 9, 2, 5, 9, 2], [6, 6], []]>


In [8]:
print(tf.strings.substr(words, 0, 1))

<tf.RaggedTensor [[b'S', b'l'], [b't', b'f', b'a', b't', b'f']]>


## 张量
由命名可知，TensorFlow是一个定义和运算涉及张量的计算的框架。TensorFlow将张量表示为基本数据类型的n维数组。
tf.Tensor具有以下属性：
+ 数据类型（float32, int32, string等）
+ 形状
一个张量中的每个元素都是一样的数据类型，且数据类型已知。形状可能已知也可能部分已知。某些情况下，只有执行图时才知道张量的形状。

一些特殊的张量：

+ tf.Variable
+ tf.constant
+ tf.placeholder
+ tf.SparseTensor



1 Rank <br>
rank是tf.Tensor对象的尺寸的数量。类似于order,degree或ｎ维。TensorFlow中的rank和数据中矩阵的秩不同。如下表所示，TensorFlow每个rank对应一个不同的数学实体。

1.1 rank 0

In [9]:
import tensorflow as tf
mammal = tf.Variable('Hongmeng', tf.string)
ignition = tf.Variable(360, tf.int16)
floating = tf.Variable(3.141592653, tf.float64)
its_complicated = tf.Variable(12.3 - 4.56j, tf.complex64)

注：在TensorFlow中，字符串被视为单个对象，而不是字符序列。可能有标量字符串，字符串向量等。

## 1.2 rank 1
要创建rank 1的tf.Tensor对象，一般传递列表作为初始值

In [10]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

## 1.3 rank 2
rank 2包含行跟列

In [11]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
print(rank_of_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

tf.Tensor(2, shape=(), dtype=int32)


1.4 高阶张量
高阶张量由n维数组组成。例如，在图像处理期间，使用了许多等级4的张量，其尺寸对应于批中示例，图像高度，图像宽度和颜色通道。

In [14]:
my_image = tf.zeros([10, 299, 299, 3])


## 1.5 获取tf.Tensor对象的rank
要确定tf.Tensor对象的rank，可以调用tf.rank方法。例如，以下方法以编程方式确定

In [15]:
r = tf.rank(my_image)
print(r)

tf.Tensor(4, shape=(), dtype=int32)


## 1.6 tf.Tensor切片
由于 tf.Tensor是n维数组，因此要访问其中的某个元素，需要指定n个索引。

对于等级0的张量（标量），不需要索引，因为它已经是一个数字。

对于秩为1的张量（向量），传递单个索引可访问数字：

In [16]:

my_scalar = first_primes[2]

对于2级或更高的张量，情况更加有趣。对于 tf.Tensor的rank为2的，传递两个数字将按预期返回标量：

In [17]:
my_scalar = mymat[1, 0]

但是，传递单个数字将返回矩阵的子向量

In [18]:
my_row_vector = mymat[1]
my_column_vector = mymat[:, 0]

In [19]:
print(my_row_vector)
print(my_column_vector)

tf.Tensor([11], shape=(1,), dtype=int32)
tf.Tensor([ 7 11], shape=(2,), dtype=int32)


## 2 形状
张量的形状是每个维度中元素的数量。TensorFlow在图形构建过程中自动推断形状。这些推断的形状可能具有已知或未知的等级。如果rank是已知的，则每个维度的大小可能是已知的或未知的。

TensorFlow文档使用三种符号约定来描述张量维数：rank，形状和维数。下表显示了它们之间的相互关系：

2.1 获取tf.Tensor对象的形状¶
有两种访问形状tf.Tensor的方法。在构建图形时，询问关于张量形状的已知知识通常很有用。

1、可以通过读取对象的shape属性来获取tf.Tensor。此方法返回一个TensorShape对象，这是表示部分指定的形状的便捷方式（因为在构建图形时，并非所有形状都将是完全已知的）。

2、也有可能在运行时获得一个代表某个张量的形状的tf.Tensor。这是通过调用tf.shape 操作来完成的。这样，可以通过构建依赖于输入的动态形状的其他张量来完成网络构建。

例如，下面是如何制作一个零向量，其大小与给定矩阵中的列数相同：

In [20]:
zeros = tf.zeros(mymat.shape[1])

In [21]:
print(zeros)

tf.Tensor([0.], shape=(1,), dtype=float32)


## 3 数据类型
除维数外，张量还具有数据类型。

具有一个以上的数据类型是不可能的。但是，可以将任意数据结构序列化为strings并将其存储在tf.Tensors中。

可以使用tf.cast命令将tf.Tensors从一种数据类型转换为另一种数据类型：

In [22]:
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)

要检查tf.Tensor的数据类型，请使用Tensor.dtype属性。

tf.Tensor从python对象创建时，可以选择指定数据类型。如果不设置，TensorFlow会选择一种可以代表数据的数据类型。TensorFlow将Python整数转换为tf.int32，并将python浮点数转换为tf.float32。而在将numpy转换为数组时使用的相同规则。

In [24]:
float_tensor.dtype

tf.float32


4 打印张量
出于调试目的，可能需要打印tf.Tensor的值。TensorFlow2中可以直接用print打印

In [25]:

t = tf.add(3, 4)
print(t)

tf.Tensor(7, shape=(), dtype=int32)


## 教程-Variables
TensorFlow 变量是表示程序所控制的共享持久状态的最佳方法。

变量通过tf.Variable类进行操作。tf.Variable 表示张量，其值可以通过在其上运行ops进行更改。特定操作允许您读取和修改此张量的值。
创建一个变量

In [26]:
import tensorflow as tf
# 要创建变量，只需提供初始值
my_var = tf.Variable(tf.ones([2,3]))
print(my_var)
#如果tf.device作用域处于活动状态，则变量将被放置在该设备上；否则，变量将被放置在与其dtype兼容的“最快”设备上
try:
    with tf.device("/device:GPU:0"):
        v = tf.Variable(tf.zeros([10, 10]))
        print(v)
except:
    print('no gpu')

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>



2 使用变量

In [27]:

# 变量相加
a = tf.Variable(1.0)
b = (a+2) *3
print(a)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
tf.Tensor(9.0, shape=(), dtype=float32)


In [28]:
# 更改某个向量
a = tf.Variable(1.0)
b = (a.assign_add(2)) *3
print(a)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
tf.Tensor(9.0, shape=(), dtype=float32)



3 变量追踪
TensorFlow中的变量是一个Python对象。在构建图层，模型，优化器和其他相关工具时，您可能希望获取（假设）模型中所有变量的列表。

In [29]:
class MyModuleOne(tf.Module):
    def __init__(self):
        self.v0 = tf.Variable(1.0)
        self.vs = [tf.Variable(x) for x in range(10)]
    
class MyOtherModule(tf.Module):
    def __init__(self):
        self.m = MyModuleOne()
        self.v = tf.Variable(10.0)
    
m = MyOtherModule()
print(m.variables)  # 模型中的所有变量
len(m.variables)

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>)


12